name: Lint and Test

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          pip install pipenv
          pipenv requirements --dev > CI_Requirements.txt
          export PATH=${PATH}:$(pwd)
          pip install -r CI_Requirements.txt

      - name: Test Format
        run: |
          pyroma .
          pylint --rcfile=setup.cfg paneldata_pipeline tests
      - name: Unittests
        run: pytest -rf --cov
